apiVersion: v1
kind: Service
metadata:
  name: demo-python-service
  labels:
    demo-python-service: latest
spec:
  selector:
    app: demo-python
  ports:
   - name: default
     port: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-python
spec:
  selector:
    matchLabels:
      app: demo-python
  replicas: 4
  template:
    metadata:
      labels:
        app: demo-python
    spec:
      containers:
      - name: demo-python
        image: billyjenkins417/demo-python:latest
        ports:
        - containerPort: 80